name: Unity CI/CD 🚀

#on: [push, pull_request]
on:
  push:
    tags:
    - "*"

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    name: Build pipeline 🛠️
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

  release:
    name: Release pipeline
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Github release
      - name: Create release
        uses: anton-yurchenko/git-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: 'false'
          PRE_RELEASE: 'false'
          CHANGELOG_FILE: 'CHANGELOG.md'
          ALLOW_EMPTY_CHANGELOG: 'false'

  github-release:
    name: Upload to github releases
    runs-on: ubuntu-latest
    steps:
      - name: Get Release url
        id: get_release
        uses: bruceadams/get-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.get_release.outputs.upload_url }}

      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@master

      - run: echo ${{ steps.get_version.outputs.version }}

      - name: Download build
        uses: actions/download-artifact@main
        with:
          name: Build

      - name: Archive build
        uses: thedoctor0/zip-release@main
        with:
          filename: release.zip
          exclusions: '*.git* /*node_modules/*'

      - name: Upload asset to Github Release
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release-v${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip